apiVersion: v1
kind: Service
metadata:
  name: demoapp-service
  labels:
    app: demoapp-project
spec:
  selector:
    app: demoapp-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31300
