apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoproject-deployment
spec:
  selector:
    matchLabels:
      app: demoproject
  replicas: 2
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: demoproject
    spec:
      containers:
      - name: demoproject
        image: k2r2t2/demoproject
        imagePullPolicy: Always
        ports:
        - containerPort: 8080


---


apiVersion: v1
kind: Service
metadata:
  name: demoproject-service
  labels:
    app: demoproject
spec:
  selector:
    app: demoproject
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
